---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/14/2023 12:41 AM
---
require('__erm_zerg__/global')
local ErmConfig = require('__enemyracemanager__/lib/global_config')
local AnimationDB = require('__erm_zerg_hd_assets__/animation_db')

local mutalisk_proj = data.raw['projectile']['mutalisk-projectile']
mutalisk_proj['animation'] = AnimationDB.get_single_animation('projectiles','mutalisk','projectile')

local hydralisk_proj = data.raw['projectile']['hydralisk-projectile']
hydralisk_proj['animation'] = AnimationDB.get_single_animation('projectiles','hydralisk','projectile')

local guardian_proj = data.raw['projectile']['guardian-projectile']
guardian_proj['animation'] = AnimationDB.get_single_animation('projectiles','guardian','projectile')

local parasite_proj = data.raw['projectile']['parasite-projectile']
parasite_proj['animation'] = AnimationDB.get_single_animation('projectiles','parasite','projectile')

local lurker_explosion = data.raw['explosion']['lurker-explosion']
lurker_explosion['animations'] = AnimationDB.get_single_animation('projectiles','lurker','explosion')

local colony_explosion = data.raw['explosion']['colony-explosion']
colony_explosion['animations'] = AnimationDB.get_layered_animations('projectiles','colony','explosion')

local mutalisk_explosion = data.raw['explosion']['mutalisk-explosion-small']
mutalisk_explosion['animations'] = AnimationDB.get_layered_animations('projectiles','mutalisk','explosion')

local hydralisk_explosion = data.raw['explosion']['hydralisk-explosion-small']
hydralisk_explosion['animations'] = AnimationDB.get_layered_animations('projectiles','hydralisk','explosion')

local blood_cloud_explosion = data.raw['explosion']['blood-cloud-explosion']
blood_cloud_explosion['animations'] = AnimationDB.get_layered_animations('projectiles','blood_cloud','explosion')

local dark_swam_80 = data.raw['explosion']['dark-swarm-80-explosion']
dark_swam_80['animations'] = AnimationDB.get_layered_animations('projectiles','dark_swam_80','explosion')

local dark_swam = data.raw['explosion']['dark-swarm-explosion']
dark_swam['animations'] = AnimationDB.get_layered_animations('projectiles','dark_swam','explosion')

local acid_cloud = data.raw['explosion']['acid-cloud-explosion']
acid_cloud['animations'] = AnimationDB.get_layered_animations('projectiles','acid_cloud','explosion')

local devourer_cloud = data.raw['explosion']['devourer-cloud-explosion']
devourer_cloud['animations'] = AnimationDB.get_layered_animations('projectiles','devourer_cloud','explosion')

local scourge_explosion = data.raw['explosion']['scourge-explosion']
scourge_explosion['animations'] = AnimationDB.get_layered_animations('projectiles','scourge_explosion','explosion')


