---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/17/2023 9:39 PM
---
---
local SharedFunctions = {}

function SharedFunctions.getSpawnerCreep()
    return {
        {
            decorative = "creep-decal",
            spawn_min = 3,
            spawn_max = 5,
            spawn_min_radius = 2,
            spawn_max_radius = 7
        },
        {
            decorative = "creep-decal-transparent",
            spawn_min = 4,
            spawn_max = 20,
            spawn_min_radius = 2,
            spawn_max_radius = 14,
            radius_curve = 0.9
        }
    }
end

return SharedFunctions

