---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 6/12/2022 7:43 PM
---

local ERM_UnitTint = require('__enemyracemanager__/lib/rig/unit_tint')
require('__erm_zerg__/global')
require('util')
local ErmConfig = require('__enemyracemanager__/lib/global_config')

--- Change name
local name = 'overmind'
local unit_scale = 0.5

--- Change collision / selection box in case the scale not match
--- Changing collision box may affect unit pathing.. Be careful when you change it.
local collision_box = { { -3.5, -4.25 }, { 3.25, 3 } }
-- Map generator bounding box should always at least 1 unit wider than collision_box. This prevent units from getting stuck.
local map_generator_bounding_box = { { -4.5, -5.25 }, { 4.25, 4 } }
local selection_box = { { -3.5, -4.25 }, { 3.25, 3 } }

--- This function convert classic to HD graphic
--- i is the level of the unit.
local convert_to_hd = function(i)
    --- Buildings are either unit-spawner or turret for enemies.
    local unit = data.raw["unit-spawner"][MOD_NAME..'/'.. name ..'/'.. i]

    unit['animations'] = {
        layers = {
            {
                filename = "__erm_zerg_hd__/graphics/entity/buildings/" .. name .. "/" .. name .. ".png",
                width = 909,
                height = 664,
                frame_count = 4,
                animation_speed = 0.2,
                direction_count = 1,
                run_mode = "forward-then-backward",
                scale = unit_scale
            },
            {
                filename = "__erm_zerg_hd__/graphics/entity/buildings/" .. name .. "/" .. name .. ".png",
                width = 909,
                height = 664,
                frame_count = 4,
                animation_speed = 0.2,
                direction_count = 1,
                run_mode = "forward-then-backward",
                scale = unit_scale,
                draw_as_shadow = true,
                shift = {0.2, 0}
            }
        }
    }

    unit['collision_box'] = collision_box
    unit['selection_box'] = selection_box
    unit['sticker_box'] = selection_box


end

--- Convert regular building, level 1 - 20
local boss_level = ErmConfig.BOSS_LEVELS

for i = 1, #boss_level do
    convert_to_hd(boss_level[i])
end
