---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 6/12/2022 7:43 PM
---

local smallCorpse = data.raw["corpse"]['zerg-small-base-corpse']

--- Replace the animation
smallCorpse['animation'] = {
    filename = "__erm_zerg_hd__/graphics/entity/buildings/death/zerg_small_rubble.png",
    variation_count = 4,
    width = 386,
    height = 377,
    frame_count = 1,
    direction_count = 1,
    scale = 0.5
}


local largeCorpse = data.raw["corpse"]['zerg-large-base-corpse']

largeCorpse['animation'] =             {
    filename = "__erm_zerg_hd__/graphics/entity/buildings/death/zerg_large_rubble.png",
    width = 509,
    height = 505,
    variation_count = 4,
    frame_count = 1,
    direction_count = 1,
    scale = 0.5
}

local explosion = data.raw["explosion"]['zerg-building-explosion']
explosion['animations'] = {
    filename = "__erm_zerg_hd__/graphics/entity/buildings/death/zerg_building_blood_large.png",
    width = 550,
    height = 656,
    frame_count = 8,
    animation_speed = 0.2,
    direction_count = 1,
    scale = 0.7
}

local xlarge_explosion =  data.raw["explosion"]['zerg-terran-building-xlarge-explosion']
xlarge_explosion['animations'] = {
    filename = "__erm_zerg_hd__/graphics/entity/buildings/death/terran_building_explosion_large.png",
    width = 819,
    height = 661,
    frame_count = 10,
    animation_speed = 0.25,
    direction_count = 1,
    scale = 0.7
}

data:extend({
    {
        type = "explosion",
        name = "zerg-building-explosion-small",
        icon = "__erm_zerg__/graphics/entity/icons/buildings/advisor.png",
        icon_size = 64,
        subgroup = 'explosions',
        flags = { "not-on-map", "hidden" },
        order = "zerg-explosions",
        render_layer = "explosion",
        animations = {
            filename = "__erm_zerg_hd__/graphics/entity/buildings/death/zerg_building_blood_small.png",
            width = 344,
            height = 342,
            frame_count = 8,
            animation_speed = 0.25,
            direction_count = 1,
            scale = 0.7
        }
    },
})
