---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 6/12/2022 7:43 PM
---

local ERM_UnitTint = require('__enemyracemanager__/lib/rig/unit_tint')
require('__erm_zerg__/global')
require('util')
local ErmConfig = require('__enemyracemanager__/lib/global_config')
local SharedFunction = require('__erm_zerg_hd__/prototypes/shared_functions')
local AnimationDB = require('__erm_zerg_hd_assets__/animation_db')

--- Change name
local name = 'spore_colony'
local unit_scale = 0.375

--- Change collision / selection box in case the scale not match
--- Changing collision box may affect unit pathing.. Be careful when you change it.
local collision_box = { { -2, -2 }, { 2, 2 } }
local map_generator_bounding_box = { { -3, -3 }, { 3, 3 } }
local selection_box = { { -2, -2 }, { 2, 2 } }

local folded_animation = function()
    local animation = AnimationDB.get_layered_animations('buildings', name, 'run')
    return animation
end

--- This function convert classic to HD graphic
--- i is the level of the unit.
local convert_to_hd = function(i)
    --- Buildings are either unit-spawner or turret for enemies.
    local turret = data.raw["turret"][MOD_NAME..'/'.. name ..'/'.. i]

    turret['folded_animation'] = folded_animation()

    turret['collision_box'] = collision_box
    turret['selection_box'] = selection_box
    turret['sticker_box'] = selection_box
    turret['map_generator_bounding_box'] = map_generator_bounding_box

    turret['dying_explosion'] = 'zerg-building-explosion-small'
end

--- Convert regular building, level 1 - 20
local max_level = ErmConfig.MAX_LEVELS

for i = 1, max_level do
    convert_to_hd(i)
end
