---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 6/12/2022 7:43 PM
---

local ERM_UnitTint = require('__enemyracemanager__/lib/rig/unit_tint')
require('__erm_zerg__/global')
require('util')
local ErmConfig = require('__enemyracemanager__/lib/global_config')

--- Change name
local name = 'spore_colony'
local unit_scale = 0.375

--- Change collision / selection box in case the scale not match
--- Changing collision box may affect unit pathing.. Be careful when you change it.
local collision_box = { { -2, -2 }, { 2, 2 } }
local map_generator_bounding_box = { { -3, -3 }, { 3, 3 } }
local selection_box = { { -2, -2 }, { 2, 2 } }

local folded_animation = function()
    return {
        layers = {
            {
                filename = "__erm_zerg_hd__/graphics/entity/buildings/" .. name .. "/" .. name .. ".png",
                run_mode = "forward",
                width = 508,
                height = 515,
                frame_count = 4,
                direction_count = 1,
                scale = unit_scale,
            },
            {
                filename = "__erm_zerg_hd__/graphics/entity/buildings/" .. name .. "/" .. name .. ".png",
                run_mode = "forward",
                width = 508,
                height = 515,
                frame_count = 4,
                direction_count = 1,
                draw_as_shadow = true,
                shift = { 0.25, 0.1 },
                scale = unit_scale,
            }
        }
    }
end

--- This function convert classic to HD graphic
--- i is the level of the unit.
local convert_to_hd = function(i)
    --- Buildings are either unit-spawner or turret for enemies.
    local turret = data.raw["turret"][MOD_NAME..'/'.. name ..'/'.. i]

    turret['folded_animation'] = folded_animation()

    turret['collision_box'] = collision_box
    turret['selection_box'] = selection_box
    turret['sticker_box'] = selection_box

    turret['dying_explosion'] = 'zerg-building-explosion-small'
end

--- Convert regular building, level 1 - 20
local max_level = ErmConfig.MAX_LEVELS

for i = 1, max_level do
    convert_to_hd(i)
end
