---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 6/12/2022 7:43 PM
---

local ERM_UnitTint = require('__enemyracemanager__/lib/rig/unit_tint')
require('__erm_zerg__/global')
require('util')
local ErmConfig = require('__enemyracemanager__/lib/global_config')

--- Change name
local name = 'sunker_colony'
local short_range_name = 'sunker_colony_shortrange'
local unit_scale = 0.375

--- Change collision / selection box in case the scale not match
--- Changing collision box may affect unit pathing.. Be careful when you change it.
local collision_box = { { -2, -2 }, { 2, 2 } }
local map_generator_bounding_box = { { -3, -3 }, { 3, 3 } }
local selection_box = { { -2, -2 }, { 2, 2 } }

local folded_animation = function()
    return {
        layers = {
            {
                filename = "__erm_zerg_hd__/graphics/entity/buildings/" .. name .. "/" .. name .. ".png",
                width = 521,
                height = 503,
                frame_count = 3,
                direction_count = 1,
                scale = unit_scale,
                run_mode = "forward-then-backward",
            },
            {
                filename = "__erm_zerg_hd__/graphics/entity/buildings/" .. name .. "/" .. name .. ".png",
                width = 521,
                height = 503,
                frame_count = 3,
                direction_count = 1,
                scale = unit_scale,
                draw_as_shadow = true,
                shift = { 0.25, 0.1 },
                run_mode = "forward-then-backward",
            },
        }
    }
end

local attack_animation = function()
    return {
        layers = {
            {
                filename = "__erm_zerg_hd__/graphics/entity/buildings/" .. name .. "/" .. name .. "_attack.png",
                width = 521,
                height = 503,
                frame_count = 11,
                direction_count = 3,
                scale = unit_scale,
                run_mode = "forward-then-backward",
            },
            {
                filename = "__erm_zerg_hd__/graphics/entity/buildings/" .. name .. "/" .. name .. "_attack.png",
                width = 521,
                height = 503,
                frame_count = 11,
                direction_count = 3,
                scale = unit_scale,
                run_mode = "forward-then-backward",
                draw_as_shadow = true,
                shift = { 0.25, 0.1 },
            },
        }
    }
end

--- This function convert classic to HD graphic
--- i is the level of the unit.
local convert_to_hd = function(i)
    --- Buildings are either unit-spawner or turret for enemies.
    local turret = data.raw["turret"][MOD_NAME..'/'.. name ..'/'.. i]

    turret['folded_animation'] = folded_animation()
    turret['starting_attack_animation'] = attack_animation()

    turret['collision_box'] = collision_box
    turret['selection_box'] = selection_box
    turret['sticker_box'] = selection_box

    turret['dying_explosion'] = 'zerg-building-explosion-small'

    local short_turret = data.raw["turret"][MOD_NAME..'/'.. short_range_name ..'/'.. i]

    short_turret['folded_animation'] = folded_animation()
    short_turret['starting_attack_animation'] = attack_animation()

    short_turret['collision_box'] = collision_box
    short_turret['selection_box'] = selection_box
    short_turret['sticker_box'] = selection_box

    turret['dying_explosion'] = 'zerg-building-explosion-small'
end

--- Convert regular building, level 1 - 20
local max_level = ErmConfig.MAX_LEVELS

for i = 1, max_level do
    convert_to_hd(i)
end
